USE DATABASE DATAOPS_DEMO;
USE SCHEMA CORE;

CREATE OR REPLACE CORTEX SEARCH SERVICE DATAOPS_EVIDENCE_SEARCH
  ON CONTENT
  ATTRIBUTES DOC_TYPE, SOURCE_SYSTEM
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 hour'
  AS (
      SELECT
          DOC_ID,
          DOC_TYPE,
          DOC_TS,
          TITLE,
          CONTENT,
          SOURCE_SYSTEM
      FROM DATAOPS_DEMO.CORE.OPERATIONAL_DOCUMENTS
  );
